# Homebrew
- homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_taps }}'
  tags: brew

- homebrew:
    name: git
    state: latest
    update_homebrew: yes
  tags: brew

- homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'
  tags: brew

- homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages }}'
  tags: brew