---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - debug: msg="Checking we are running in the directory of the script"
      failed_when: not ansible_env.PWD.endswith('/mac-ansible-setup')

- hosts: 127.0.0.1
  connection: local
  roles:
    - name: susy_osx
      when: ansible_distribution == 'MacOSX'